calibration_dataset:
  dataset_info: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/run/20230324-115040/yolox_s_lite/compilation/TDA4VM/wk/od-8220/dataset.yaml
  name: modelmaker
  num_classes: 90
  num_frames: 10
  path: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/dataset
  shuffle: true
  split: train
dataset_category: coco
input_dataset:
  dataset_info: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/run/20230324-115040/yolox_s_lite/compilation/TDA4VM/wk/od-8220/dataset.yaml
  name: modelmaker
  num_classes: 90
  num_frames: 51
  path: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/dataset
  shuffle: false
  split: val
metric:
  label_offset_pred: 0
  run_dir: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/run/20230324-115040/yolox_s_lite/compilation/TDA4VM/wk/od-8220
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: null
  model_shortlist: 10
postprocess:
  detection_threshold: 0.6
  formatter:
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
    src_indices:
    - 5
    - 4
  ignore_index: null
  normalized_detections: false
  resize_with_pad: true
  save_output: true
  shuffle_indices: null
  squeeze_axis: null
preprocess:
  add_flip_image: false
  backend: cv2
  crop: 640
  data_layout: NCHW
  interpolation: null
  pad_color:
  - 114
  - 114
  - 114
  resize: 640
  resize_with_pad:
  - true
  - corner
  reverse_channels: true
session:
  artifacts_folder: artifacts
  extra_inputs: null
  input_data_layout: NCHW
  input_mean: null
  input_optimization: true
  input_scale: null
  input_shape:
    inputNet_IN:
    - 1
    - 3
    - 640
    - 640
  model_file: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/run/20230324-115040/yolox_s_lite/compilation/TDA4VM/wk/od-8220/model/model.onnx
  model_folder: model
  model_id: od-8220
  model_path: model/model.onnx
  model_type: null
  num_inputs: 1
  num_tidl_subgraphs: 16
  output_shape: null
  run_dir: od-8220
  run_dir_tree_depth: 3
  run_suffix: null
  runtime_options:
    accuracy_level: 1
    advanced_options:activation_clipping: 1
    advanced_options:add_data_convert_ops: 3
    advanced_options:bias_calibration: 1
    advanced_options:calibration_frames: 10
    advanced_options:calibration_iterations: 10
    advanced_options:channel_wise_quantization: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:output_feature_16bit_names_list: 1213, 1212, 1211, 1197, 1196,
      1195, 1181, 1180, 1179
    advanced_options:params_16bit_names_list: ''
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:quantization_scale_type: 0
    advanced_options:weight_clipping: 1
    artifacts_folder: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/run/20230324-115040/yolox_s_lite/compilation/TDA4VM/wk/od-8220/artifacts
    debug_level: 0
    import: 'no'
    object_detection:confidence_threshold: 0.6
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/run/20230324-115040/yolox_s_lite/compilation/TDA4VM/wk/od-8220/model/model.prototxt
    object_detection:top_k: 200
    platform: J7
    priority: 0
    tensor_bits: 8
    tidl_tools_path: ../edgeai-benchmark/tools/TDA4VM/tidl_tools
    version: '8.2'
  session_name: onnxrt
  supported_machines: null
  target_device: TDA4VM
  target_machine: pc
  tensor_bits: 8
  tidl_offload: true
  tidl_tools_path: ../edgeai-benchmark/tools/TDA4VM/tidl_tools
  work_dir: /home/a0504102/model-training/edgeai-modelmaker/data/projects/alpd_250_dataset/run/20230324-115040/yolox_s_lite/compilation/TDA4VM/wk
task_type: licence_plate_recognition
#task_type: detection
