title: "RPi Camera"
log_level: 2
inputs:
    # rpi camera is supported only in Starter Kit
    # rpiV2 camera should be connected to CAM1 rpi header on SK
    # k3-j721e-sk-rpi-cam-imx219.dtbo should be applied in uenv.txt
    input0:
        source: /dev/video-rpi-cam0
        subdev-id: /dev/v4l-rpi-subdev0
        width: 1920
        height: 1080
        format: rggb
        framerate: 30
models:
    model0:
        model_path: /opt/model_zoo/TVM-CL-3090-mobileNetV2-tv
        topN: 5
    model1:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz_threshold: 0.6
    model2:
        model_path: /opt/model_zoo/ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512
        alpha: 0.4
outputs:
    output0:
        sink: kmssink
        width: 1920
        height: 1080
        overlay-perf-type: graph
    output1:
        sink: /opt/edgeai-test-data/output/output_video.mkv
        width: 1920
        height: 1080
    output2:
        sink: /opt/edgeai-test-data/output/output_image_%04d.jpg
        width: 1920
        height: 1080
    output3:
        sink: remote
        width: 1920
        height: 1080
        port: 8081
        host: 127.0.0.1
        encoding: jpeg
        overlay-perf-type: graph

flows:
    flow0: [input0,model1,output0,[320,150,1280,720]]
