title: "RTSP stream"
log_level: 2
inputs:
    # https://gist.github.com/Santiago-vdk/80c378a315722a1b813ae5da1661f890
    # Steps given in the above url can be used to create an rtsp src in a
    # linux machine
    input0:
        source: rtsp://10.24.51.126:8554/test # rtsp stream url
        width: 1280
        height: 720
        framerate: 30
        loop: True
models:
    model0:
        model_path: /opt/model_zoo/ONR-CL-6360-regNetx-200mf
        topN: 5
    model1:
        model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.6
    model2:
        model_path: /opt/model_zoo/ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512
        alpha: 0.4
outputs:
    output0:
        sink: kmssink
        width: 1920
        height: 1080
        overlay-perf-type: graph
    output1:
        sink: /opt/edgeai-test-data/output/output_video.mkv
        width: 1920
        height: 1080
    output2:
        sink: /opt/edgeai-test-data/output/output_image_%04d.jpg
        width: 1920
        height: 1080
    output3:
        sink: remote
        width: 1920
        height: 1080
        port: 8081
        host: 127.0.0.1
        encoding: jpeg
        overlay-perf-type: graph

flows:
    flow0: [input0,model0,output0,[320,150,1280,720]]
        
